DROP DATABASE IF EXISTS hospital;

CREATE DATABASE hospital;

USE `hospital`;

CREATE TABLE `member` (
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	regDate DATETIME NOT NULL,
	`name` CHAR(100) NOT NULL,
	loginId CHAR(100) NOT NULL,
	logidPw CHAR(100) NOT NULL,
	email CHAR(100) NOT NULL,
	staffId INT(10) UNSIGNED NOT NULL, # 일반회원은 0
	PRIMARY KEY (id)
);


CREATE TABLE counselReservation (
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	regDate DATETIME NOT NULL,
	clientMemberId INT(10) UNSIGNED NOT NULL,
	staffScheduleId INT(10) UNSIGNED NOT NULL,
	`body` TEXT NOT NULL,
	PRIMARY KEY(id)
);


CREATE TABLE `staff` (
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	regDate DATETIME NOT NULL,
	`name` CHAR(100) NOT NULL,
	staffType CHAR(100) NOT NULL,
	`medicalDeptId` INT(10) UNSIGNED NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE `dept` (
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	regDate DATETIME NOT NULL,
	`name` CHAR(100) NOT NULL,
	centerId INT(10) UNSIGNED NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE `center` (
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	regDate DATETIME NOT NULL,
	`name` CHAR(100) NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE `staffSchedule`(
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT, # 1
	`regDate` DATETIME NOT NULL, # 2019-08-08 12:56:00
	`deptId` INT(10) UNSIGNED NOT NULL, # 1
	`staffId` INT(10) UNSIGNED NOT NULL, # 23
	`startTime` DATETIME NOT NULL, # 2019-08-09 13:30:00
	`endTime` DATETIME NOT NULL, # 2019-08-09 15:30:00
	`scheduleType` CHAR(100) NOT NULL, # counsel
	`relType` CHAR(100) NOT NULL, # 'counselReservation'
	`relId` INT(10) UNSIGNED NOT NULL, # 99
	PRIMARY KEY(id)
);

SHOW TABLES;


